### ISSUE TITLE
GlazeWM crashes after closing ignore/set floating windows that are in certain situations

### ISSUE THREAD

**Issue by Fuann-Kinoko** [lars-berger/GlazeWM#149]
In some applications, if the application has two windows, one is set to set floating and the other is managed normally, closing the floating window first and then the normal window will cause glazeWM to crash

So far I've only found one application, Tencent QQ, that has this problem.

Reproduction steps.
1. Open chat window
2. Double click on a picture to open the picture viewer (this viewer is set to ignore/set floating)
3. Close the image viewer
4. Close the chat window
5. All the remaining windows are no longer managed and can be dragged around. If you switch workspace via shortcut keys, there will be no response, and clicking on the topbar to switch workspace will cause an error. 

Notably, the chat window and image viewer have the same class, pid and exe. I can only match the image viewer by match_title

![](https://p.sda1.dev/7/ef27a829a9418efaea9f1a432104e138/ezgif-4-d5c15c29e2.gif)

```
2022/10/18 17:27:59
System.NullReferenceException: Object reference not set to an instance of an object.
   at GlazeWM.Domain.Containers.ContainerService.GetXOfResizableContainer(Container container) in C:\Projects\GlazeWM\GlazeWM.Domain\Containers\ContainerService.cs:line 85
   at GlazeWM.Domain.Containers.CommandHandlers.RedrawContainersHandler.SetWindowPosition(Window window, SWP flags) in C:\Projects\GlazeWM\GlazeWM.Domain\Containers\CommandHandlers\RedrawContainersHandler.cs:line 95
   at GlazeWM.Domain.Containers.CommandHandlers.RedrawContainersHandler.Handle(RedrawContainersCommand command) in C:\Projects\GlazeWM\GlazeWM.Domain\Containers\CommandHandlers\RedrawContainersHandler.cs:line 51
   at GlazeWM.Infrastructure.Bussing.Bus.Invoke[T](T command) in C:\Projects\GlazeWM\GlazeWM.Infrastructure\Bussing\Bus.cs:line 39
   at GlazeWM.Domain.Workspaces.CommandHandlers.FocusWorkspaceHandler.Handle(FocusWorkspaceCommand command) in C:\Projects\GlazeWM\GlazeWM.Domain\Workspaces\CommandHandlers\FocusWorkspaceHandler.cs:line 76
   at GlazeWM.Infrastructure.Bussing.Bus.Invoke[T](T command) in C:\Projects\GlazeWM\GlazeWM.Infrastructure\Bussing\Bus.cs:line 39
   at GlazeWM.Bar.Components.WorkspacesComponentViewModel.FocusWorkspace(String workspaceName) in C:\Projects\GlazeWM\GlazeWM.Bar\Components\WorkspacesComponentViewModel.cs:line 78
   at GlazeWM.Bar.Common.RelayCommand`1.Execute(Object parameter) in C:\Projects\GlazeWM\GlazeWM.Bar\Common\RelayCommand.cs:line 72
   at MS.Internal.Commands.CommandHelpers.CriticalExecuteCommandSource(ICommandSource commandSource, Boolean userInitiated)
   at System.Windows.Controls.Primitives.ButtonBase.OnClick()
   at System.Windows.Controls.Button.OnClick()
   at System.Windows.Controls.Primitives.ButtonBase.OnMouseLeftButtonUp(MouseButtonEventArgs e)
   at System.Windows.UIElement.OnMouseLeftButtonUpThunk(Object sender, MouseButtonEventArgs e)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.ReRaiseEventAs(DependencyObject sender, RoutedEventArgs args, RoutedEvent newEvent)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.UIElement.RaiseTrustedEvent(RoutedEventArgs args)
   at System.Windows.Input.InputManager.ProcessStagingArea()
   at System.Windows.Input.InputProviderSite.ReportInput(InputReport inputReport)
   at System.Windows.Interop.HwndMouseInputProvider.ReportInput(IntPtr hwnd, InputMode mode, Int32 timestamp, RawMouseActions actions, Int32 x, Int32 y, Int32 wheel)
   at System.Windows.Interop.HwndMouseInputProvider.FilterMessage(IntPtr hwnd, WindowMessage msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at System.Windows.Interop.HwndSource.InputFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   at System.Windows.Threading.Dispatcher.PushFrame(DispatcherFrame frame)
   at System.Windows.Threading.Dispatcher.Run()
   at System.Windows.Application.RunDispatcher(Object ignore)
   at System.Windows.Application.RunInternal(Window window)
   at System.Windows.Application.Run()
   at GlazeWM.Bar.BarService.<StartApp>b__6_0() in C:\Projects\GlazeWM\GlazeWM.Bar\BarService.cs:line 52
State dump: {"X":0,"Y":0,"Width":0,"Height":0,"__type":"RootContainer","FocusIndex":0,"Children":[{"X":0,"Y":0,"Width":1920,"Height":1020,"__type":"Monitor","FocusIndex":0,"DeviceName":"\\\\.\\DISPLAY1","Children":[{"X":15,"Y":60,"Width":1890,"Height":945,"__type":"Workspace","FocusIndex":1,"Name":"2","Children":[{"X":0,"Y":0,"Width":0,"Height":0,"__type":"MinimizedWindow","FocusIndex":1,"Handle":"1e12d6","FloatingPlacement":{"Left":650,"Top":60,"Right":1270,"Bottom":1005,"X":650,"Y":60,"Width":620,"Height":945},"BorderDelta":{"Left":0,"Top":0,"Right":0,"Bottom":0},"PreviousState":"TILING","Children":[]},{"X":15,"Y":60,"Width":1890,"Height":945,"__type":"TilingWindow","FocusIndex":0,"Handle":"61190","FloatingPlacement":{"Left":643,"Top":56,"Right":1277,"Bottom":1008,"X":643,"Y":56,"Width":634,"Height":952},"BorderDelta":{"Left":7,"Top":0,"Right":7,"Bottom":7},"SizePercentage":1,"Children":[]}]},{"X":15,"Y":60,"Width":1890,"Height":945,"__type":"Workspace","FocusIndex":0,"Name":"3","Children":[{"X":15,"Y":60,"Width":1890,"Height":945,"__type":"TilingWindow","FocusIndex":0,"Handle":"240f74","FloatingPlacement":{"Left":485,"Top":55,"Right":1436,"Bottom":1009,"X":485,"Y":55,"Width":951,"Height":954},"BorderDelta":{"Left":7,"Top":0,"Right":7,"Bottom":7},"SizePercentage":1,"Children":[]}]},{"X":15,"Y":60,"Width":1890,"Height":945,"__type":"Workspace","FocusIndex":2,"Name":"4","Children":[{"X":15,"Y":60,"Width":1890,"Height":945,"__type":"TilingWindow","FocusIndex":0,"Handle":"12137c","FloatingPlacement":{"Left":492,"Top":60,"Right":1429,"Bottom":1005,"X":492,"Y":60,"Width":937,"Height":945},"BorderDelta":{"Left":7,"Top":0,"Right":7,"Bottom":7},"SizePercentage":1,"Children":[]}]}]},{"X":-1920,"Y":0,"Width":1920,"Height":1080,"__type":"Monitor","FocusIndex":1,"DeviceName":"\\\\.\\DISPLAY2","Children":[{"X":-1905,"Y":60,"Width":1890,"Height":1005,"__type":"Workspace","FocusIndex":0,"Name":"1","Children":[{"X":-1905,"Y":60,"Width":1890,"Height":1005,"__type":"TilingWindow","FocusIndex":0,"Handle":"d096e","FloatingPlacement":{"Left":-1905,"Top":60,"Right":-15,"Bottom":1065,"X":-1905,"Y":60,"Width":1890,"Height":1005},"BorderDelta":{"Left":7,"Top":0,"Right":7,"Bottom":7},"SizePercentage":1,"Children":[]}]}]}]}
```

**Comment by Fuann-Kinoko** [comment]
In version 1.7.1, when the image viewer is matched by set floating, it crashes as soon as the image viewer is opened. But if it is matched by ignore, everything is fine

In 1.8, it crashes regardless of whether it is set floating or ignore

**Comment by ParasiteDelta** [comment]
Better wording for the same issue in #144, still a bit weird how this happens. Hopefully it's fixable.

**Comment by lars-berger** [comment]
Ah, I've found the issue now. Will try to get a fix out ASAP 👍 

The error happens in some cases when applying multiple window rules (eg. [`set floating`, `resize borders 0px -7px -7px -7px`]). For example, the Affinity Designer error doesn't actually occur if you don't add a custom window rule for resizing the borders.

**Comment by lars-berger** [comment]
This has been fixed in the [latest release](https://github.com/lars-berger/GlazeWM/releases) 🎉
