### ISSUE TITLE
`cursor_follows_focus` stops working for v1.11.1

### ISSUE THREAD

**Issue by Fuann-Kinoko** [lars-berger/GlazeWM#298]
`cursor_follows_focus` works fine in v1.11.0
But it seems that in v1.11.1, this function does not work anymore

it doesnt work for the build from master branch either

**Comment by lars-berger** [comment]
There were some crashes that were happening because of that feature, so it was removed in v1.11.0. It'll get added back in the next release - there's currently a PR for it here #247

**Comment by Fuann-Kinoko** [comment]
> There were some crashes that were happening because of that feature, so it was removed in v1.11.1. It'll get added back in the next release - there's currently a PR for it here #247

That does seem to be the case
I tried the `cursor_follows_focus` function that just merged and it seems that every `set floating` window causes crashes

```
System.NullReferenceException: Object reference not set to an instance of an object.
   at GlazeWM.Domain.Containers.ContainerService.GetXOfResizableContainer(Container container) in D:\glazeWM\workspace\GlazeWM\GlazeWM.Domain\Containers\ContainerService.cs:line 101
   at GlazeWM.Domain.Containers.Container.ToRect() in D:\glazeWM\workspace\GlazeWM\GlazeWM.Domain\Containers\Container.cs:line 161
   at GlazeWM.Domain.Containers.CommandHandlers.CenterCursorOnContainerHandler.Handle(CenterCursorOnContainerCommand command) in D:\glazeWM\workspace\GlazeWM\GlazeWM.Domain\Containers\CommandHandlers\CenterCursorOnContainerHandler.cs:line 35
   at GlazeWM.Infrastructure.Bussing.Bus.Invoke[T](T command) in D:\glazeWM\workspace\GlazeWM\GlazeWM.Infrastructure\Bussing\Bus.cs:line 48
   at GlazeWM.Infrastructure.Bussing.Bus.<>c__DisplayClass6_0`1.<InvokeAsync>b__0() in D:\glazeWM\workspace\GlazeWM\GlazeWM.Infrastructure\Bussing\Bus.cs:line 61
Command history: HandleFatalExceptionCommand, CenterCursorOnContainerCommand, SetNativeFocusCommand, RedrawContainersCommand, RedrawContainersCommand, ReplaceContainerCommand, ResizeContainerCommand, AttachContainerCommand, AttachAndResizeContainerCommand, DetachContainerCommand, DetachAndResizeContainerCommand, MoveContainerWithinTreeCommand, SetFloatingCommand, RunWindowRulesCommand, SetFocusedDescendantCommand 
State dump: {"X":0,"Y":0,"Width":0,"Height":0,"__type":"RootContainer","FocusIndex":0,"Children":[{"X":0,"Y":50,"Width":1920,"Height":1030,"__type":"Monitor","FocusIndex":0,"DeviceName":"\\\\.\\DISPLAY1","Children":[{"X":20,"Y":108,"Width":1880,"Height":952,"__type":"Workspace","FocusIndex":0,"Name":"1","Children":[{"X":20,"Y":108,"Width":613,"Height":952,"__type":"TilingWindow","FocusIndex":1,"Handle":263906,"FloatingPlacement":{"Left":20,"Top":106,"Right":1900,"Bottom":1062,"X":20,"Y":106,"Width":1880,"Height":956},"BorderDelta":{"Left":7,"Top":0,"Right":7,"Bottom":7},"SizePercentage":0.3333333333333333,"Children":[]},{"X":653,"Y":108,"Width":613,"Height":952,"__type":"TilingWindow","FocusIndex":2,"Handle":132474,"FloatingPlacement":{"Left":20,"Top":106,"Right":1900,"Bottom":1062,"X":20,"Y":106,"Width":1880,"Height":956},"BorderDelta":{"Left":0,"Top":0,"Right":0,"Bottom":0},"SizePercentage":0.33333333333333337,"Children":[]},{"X":1286,"Y":108,"Width":613,"Height":952,"__type":"TilingWindow","FocusIndex":3,"Handle":722252,"FloatingPlacement":{"Left":20,"Top":106,"Right":1900,"Bottom":1062,"X":20,"Y":106,"Width":1880,"Height":956},"BorderDelta":{"Left":7,"Top":0,"Right":7,"Bottom":7},"SizePercentage":0.33333333333333337,"Children":[]},{"X":534,"Y":247,"Width":852,"Height":674,"__type":"FloatingWindow","FocusIndex":0,"Handle":855318,"FloatingPlacement":{"Left":534,"Top":247,"Right":1386,"Bottom":921,"X":534,"Y":247,"Width":852,"Height":674},"BorderDelta":{"Left":7,"Top":0,"Right":7,"Bottom":7},"Children":[]}]},{"X":20,"Y":108,"Width":1880,"Height":952,"__type":"Workspace","FocusIndex":1,"Name":"3","Children":[{"X":20,"Y":108,"Width":930,"Height":952,"__type":"TilingWindow","FocusIndex":1,"Handle":1248450,"FloatingPlacement":{"Left":341,"Top":262,"Right":1580,"Bottom":906,"X":341,"Y":262,"Width":1239,"Height":644},"BorderDelta":{"Left":7,"Top":0,"Right":7,"Bottom":7},"SizePercentage":0.5,"Children":[]},{"X":970,"Y":108,"Width":930,"Height":952,"__type":"TilingWindow","FocusIndex":0,"Handle":1180282,"FloatingPlacement":{"Left":341,"Top":262,"Right":1580,"Bottom":906,"X":341,"Y":262,"Width":1239,"Height":644},"BorderDelta":{"Left":7,"Top":0,"Right":7,"Bottom":7},"SizePercentage":0.5,"Children":[]}]}]}]}
```
