### ISSUE TITLE
bug: glaze crashes with cpu component enabled

### ISSUE THREAD

**Issue by Dimfred** [lars-berger/GlazeWM#353]
Hi,
when starting Glaze with the new cpu component, it crashes.
Any ideas?

I crosscompiled the `main@47bf7b4d` in WSL.

My component config:

```
    - type: "cpu"
      label: "⏽ ﬙ {percent_usage}% "
      refresh_interval_ms: 1000 # How often this counter is refreshed
```

Full log:

```
08/11/2023 19:38:34[IpcServerManager] Started IPC server on port 6123.
08/11/2023 19:38:34[Bus] Command PopulateInitialStateCommand invoked.
08/11/2023 19:38:34[Bus] Command EvaluateUserConfigCommand invoked.
08/11/2023 19:38:35[Bus] Command RegisterKeybindingsCommand invoked.
08/11/2023 19:38:35[Bus] Command AddMonitorCommand invoked.
08/11/2023 19:38:35[Bus] Command AttachContainerCommand invoked.
08/11/2023 19:38:35[Bus] Command ActivateWorkspaceCommand invoked.
08/11/2023 19:38:35[Bus] Command AttachContainerCommand invoked.
08/11/2023 19:38:35[Bus] Command AddMonitorCommand invoked.
08/11/2023 19:38:35[Bus] Command AttachContainerCommand invoked.
08/11/2023 19:38:35[Bus] Command ActivateWorkspaceCommand invoked.
08/11/2023 19:38:35[Bus] Command AttachContainerCommand invoked.
Unhandled exception. Vostok.Sys.Metrics.PerfCounters.Exceptions.InvalidInstanceException: Instance with name '_Total' doesn't exists.
at Vostok.Sys.Metrics.PerfCounters.Implementations.SingleValuePerformanceCounter`1.Collect()
at Vostok.Sys.Metrics.PerfCounters.Implementations.SingleValuePerformanceCounter`1.RawObserve()
at Vostok.Sys.Metrics.PerfCounters.Implementations.SingleValuePerformanceCounter`1.Observe()
at GlazeWM.Infrastructure.WindowsApi.CpuStatsService.GetCpuUsage() in /home/dimfred/workspaces/GlazeWM/GlazeWM.Infrastructure/WindowsApi/CpuStatsService.cs:line 33
at GlazeWM.Bar.Components.CpuComponentViewModel.<CreateLabel>b__7_0() in /home/dimfred/workspaces/GlazeWM/GlazeWM.Bar/Components/CpuComponentViewModel.cs:line 44
at GlazeWM.Bar.XamlHelper.ParseLabel(String labelString, Dictionary`2 labelVariables, ComponentViewModel viewModel) in /home/dimfred/workspaces/GlazeWM/GlazeWM.Bar/XamlHelper.cs:line 71
at GlazeWM.Bar.Components.CpuComponentViewModel.CreateLabel() in /home/dimfred/workspaces/GlazeWM/GlazeWM.Bar/Components/CpuComponentViewModel.cs:line 48
at GlazeWM.Bar.Components.CpuComponentViewModel.<.ctor>b__6_0(Int64 _) in /home/dimfred/workspaces/GlazeWM/GlazeWM.Bar/Components/CpuComponentViewModel.cs:line 35
at System.Reactive.AnonymousSafeObserver`1.OnNext(T value) in /_/Rx.NET/Source/src/System.Reactive/AnonymousSafeObserver.cs:line 43
at System.Reactive.Sink`1.ForwardOnNext(TTarget value) in /_/Rx.NET/Source/src/System.Reactive/Internal/Sink.cs:line 49
at System.Reactive.HalfSerializer.ForwardOnNext[T](ISink`1 sink, T item, Int32& wip, Exception& error) in /_/Rx.NET/Source/src/System.Reactive/Internal/HalfSerializer.cs:line 36
at System.Reactive.Linq.ObservableImpl.TakeUntil`2._.OnNext(TSource value) in /_/Rx.NET/Source/src/System.Reactive/Linq/Observable/TakeUntil.cs:line 57
at System.Reactive.Sink`1.ForwardOnNext(TTarget value) in /_/Rx.NET/Source/src/System.Reactive/Internal/Sink.cs:line 49
at System.Reactive.Linq.ObservableImpl.Timer.Periodic._.InvokeStart(IScheduler self) in /_/Rx.NET/Source/src/System.Reactive/Linq/Observable/Timer.cs:line 232
--- End of stack trace from previous location ---
at System.Reactive.PlatformServices.ExceptionServicesImpl.Rethrow(Exception exception) in /_/Rx.NET/Source/src/System.Reactive/Internal/ExceptionServicesImpl.cs:line 19
at System.Reactive.ExceptionHelpers.Throw(Exception exception) in /_/Rx.NET/Source/src/System.Reactive/Internal/ExceptionServices.cs:line 16
at System.Reactive.Linq.ObservableImpl.Timer.Periodic._.InvokeStart(IScheduler self) in /_/Rx.NET/Source/src/System.Reactive/Linq/Observable/Timer.cs:line 237
at System.Reactive.Linq.ObservableImpl.Timer.Periodic._.<>c.<Run>b__4_1(IScheduler innerScheduler, _ this) in /_/Rx.NET/Source/src/System.Reactive/Linq/Observable/Timer.cs:line 145
at System.Reactive.Concurrency.UserWorkItem`1.Run() in /_/Rx.NET/Source/src/System.Reactive/Concurrency/UserWorkItem.cs:line 29
at System.Reactive.Concurrency.DefaultScheduler.<>c__5`1.<Schedule>b__5_0(Object closureWorkItem) in /_/Rx.NET/Source/src/System.Reactive/Concurrency/DefaultScheduler.cs:line 45
at System.Reactive.Concurrency.ConcurrencyAbstractionLayerImpl.<>c.<QueueUserWorkItem>b__3_0(Object itemObject) in /_/Rx.NET/Source/src/System.Reactive/Concurrency/ConcurrencyAbstractionLayerImpl.cs:line 57
at System.Threading.QueueUserWorkItemCallback.Execute()
at System.Threading.ThreadPoolWorkQueue.Dispatch()
at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart()
08/11/2023 19:38:35[Bus] Command AddMonitorCommand invoked.
08/11/2023 19:38:35[Bus] Command AttachContainerCommand invoked.
08/11/2023 19:38:35[Bus] Command ActivateWorkspaceCommand invoked.
08/11/2023 19:38:35[Bus] Command AttachContainerCommand invoked.
Unhandled exception. Vostok.Sys.Metrics.PerfCounters.Exceptions.InvalidInstanceException: Instance with name '_Total' doesn't exists.
at Vostok.Sys.Metrics.PerfCounters.Implementations.SingleValuePerformanceCounter`1.Collect()
at Vostok.Sys.Metrics.PerfCounters.Implementations.SingleValuePerformanceCounter`1.RawObserve()
at Vostok.Sys.Metrics.PerfCounters.Implementations.SingleValuePerformanceCounter`1.Observe()
at GlazeWM.Infrastructure.WindowsApi.CpuStatsService.GetCpuUsage() in /home/dimfred/workspaces/GlazeWM/GlazeWM.Infrastructure/WindowsApi/CpuStatsService.cs:line 33
at GlazeWM.Bar.Components.CpuComponentViewModel.<CreateLabel>b__7_0() in /home/dimfred/workspaces/GlazeWM/GlazeWM.Bar/Components/CpuComponentViewModel.cs:line 44
at GlazeWM.Bar.XamlHelper.ParseLabel(String labelString, Dictionary`2 labelVariables, ComponentViewModel viewModel) in /home/dimfred/workspaces/GlazeWM/GlazeWM.Bar/XamlHelper.cs:line 71
at GlazeWM.Bar.Components.CpuComponentViewModel.CreateLabel() in /home/dimfred/workspaces/GlazeWM/GlazeWM.Bar/Components/CpuComponentViewModel.cs:line 48
at GlazeWM.Bar.Components.CpuComponentViewModel.<.ctor>b__6_0(Int64 _) in /home/dimfred/workspaces/GlazeWM/GlazeWM.Bar/Components/CpuComponentViewModel.cs:line 35
at System.Reactive.AnonymousSafeObserver`1.OnNext(T value) in /_/Rx.NET/Source/src/System.Reactive/AnonymousSafeObserver.cs:line 43
at System.Reactive.Sink`1.ForwardOnNext(TTarget value) in /_/Rx.NET/Source/src/System.Reactive/Internal/Sink.cs:line 49
at System.Reactive.HalfSerializer.ForwardOnNext[T](ISink`1 sink, T item, Int32& wip, Exception& error) in /_/Rx.NET/Source/src/System.Reactive/Internal/HalfSerializer.cs:line 36
at System.Reactive.Linq.ObservableImpl.TakeUntil`2._.OnNext(TSource value) in /_/Rx.NET/Source/src/System.Reactive/Linq/Observable/TakeUntil.cs:line 57
at System.Reactive.Sink`1.ForwardOnNext(TTarget value) in /_/Rx.NET/Source/src/System.Reactive/Internal/Sink.cs:line 49
at System.Reactive.Linq.ObservableImpl.Timer.Periodic._.InvokeStart(IScheduler self) in /_/Rx.NET/Source/src/System.Reactive/Linq/Observable/Timer.cs:line 232
--- End of stack trace from previous location ---
at System.Reactive.PlatformServices.ExceptionServicesImpl.Rethrow(Exception exception) in /_/Rx.NET/Source/src/System.Reactive/Internal/ExceptionServicesImpl.cs:line 19
at System.Reactive.ExceptionHelpers.Throw(Exception exception) in /_/Rx.NET/Source/src/System.Reactive/Internal/ExceptionServices.cs:line 16
at System.Reactive.Linq.ObservableImpl.Timer.Periodic._.InvokeStart(IScheduler self) in /_/Rx.NET/Source/src/System.Reactive/Linq/Observable/Timer.cs:line 237
at System.Reactive.Linq.ObservableImpl.Timer.Periodic._.<>c.<Run>b__4_1(IScheduler innerScheduler, _ this) in /_/Rx.NET/Source/src/System.Reactive/Linq/Observable/Timer.cs:line 145
at System.Reactive.Concurrency.UserWorkItem`1.Run() in /_/Rx.NET/Source/src/System.Reactive/Concurrency/UserWorkItem.cs:line 29
at System.Reactive.Concurrency.DefaultScheduler.<>c__5`1.<Schedule>b__5_0(Object closureWorkItem) in /_/Rx.NET/Source/src/System.Reactive/Concurrency/DefaultScheduler.cs:line 45
at System.Reactive.Concurrency.ConcurrencyAbstractionLayerImpl.<>c.<QueueUserWorkItem>b__3_0(Object itemObject) in /_/Rx.NET/Source/src/System.Reactive/Concurrency/ConcurrencyAbstractionLayerImpl.cs:line 57
at System.Threading.QueueUserWorkItemCallback.Execute()
at System.Threading.ThreadPoolWorkQueue.Dispatch()
at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart()
08/11/2023 19:38:35[Bus] Command ManageWindowCommand invoked.
08/11/2023 19:38:35[ManageWindowHandler] New window managed: powershell ConsoleWindowClass
08/11/2023 19:38:35[Bus] Command AttachAndResizeContainerCommand invoked.
08/11/2023 19:38:35[Bus] Command AttachContainerCommand invoked.
08/11/2023 19:38:35[Bus] Command SetFocusedDescendantCommand invoked.
08/11/2023 19:38:35[Bus] Command RunWindowRulesCommand invoked.
08/11/2023 19:38:35[Bus] Command SetNativeFocusCommand invoked.
08/11/2023 19:38:35[Bus] Command ManageWindowCommand invoked.
08/11/2023 19:38:35[ManageWindowHandler] New window managed: kmonad ConsoleWindowClass
08/11/2023 19:38:35[Bus] Command AttachContainerCommand invoked.
08/11/2023 19:38:35[Bus] Command SetFocusedDescendantCommand invoked.
08/11/2023 19:38:35[Bus] Command RunWindowRulesCommand invoked.
08/11/2023 19:38:35[Bus] Command SetMinimizedCommand invoked.
08/11/2023 19:38:35[Bus] Command SetNativeFocusCommand invoked.
08/11/2023 19:38:35[Bus] Command ManageWindowCommand invoked.
08/11/2023 19:38:35[ManageWindowHandler] New window managed: OUTLOOK rctrl_renwnd32
08/11/2023 19:38:35[Bus] Command AttachAndResizeContainerCommand invoked.
08/11/2023 19:38:35[Bus] Command AttachContainerCommand invoked.
08/11/2023 19:38:35[Bus] Command SetFocusedDescendantCommand invoked.
08/11/2023 19:38:35[Bus] Command RunWindowRulesCommand invoked.
08/11/2023 19:38:35[Bus] Command ResizeWindowBordersCommand invoked.
08/11/2023 19:38:35[Bus] Command RedrawContainersCommand invoked.
08/11/2023 19:38:35[Bus] Command FocusWorkspaceCommand invoked.
08/11/2023 19:38:35[Bus] Command ActivateWorkspaceCommand invoked.
08/11/2023 19:38:35[Bus] Command AttachContainerCommand invoked.
08/11/2023 19:38:35[FocusWorkspaceHandler] WorkspaceToFocus: 10
08/11/2023 19:38:35[Bus] Command SetFocusedDescendantCommand invoked.
08/11/2023 19:38:35[Bus] Command RedrawContainersCommand invoked.
08/11/2023 19:38:35[Bus] Command SetNativeFocusCommand invoked.
08/11/2023 19:38:35[Bus] Command SetFocusedDescendantCommand invoked.
08/11/2023 19:38:35[Bus] Command MoveWindowToWorkspaceCommand invoked.
08/11/2023 19:38:35[Bus] Command MoveContainerWithinTreeCommand invoked.
08/11/2023 19:38:35[Bus] Command DetachAndResizeContainerCommand invoked.
08/11/2023 19:38:35[Bus] Command DetachContainerCommand invoked.
08/11/2023 19:38:35[Bus] Command AttachAndResizeContainerCommand invoked.
08/11/2023 19:38:35[Bus] Command AttachContainerCommand invoked.
08/11/2023 19:38:35[Bus] Command SetFocusedDescendantCommand invoked.
08/11/2023 19:38:35[Bus] Command SetNativeFocusCommand invoked.
08/11/2023 19:38:35[Bus] Command SetFocusedDescendantCommand invoked.
08/11/2023 19:38:35[Bus] Command RedrawContainersCommand invoked.
08/11/2023 19:38:35[Bus] Command FocusWorkspaceRecentCommand invoked.
08/11/2023 19:38:35[Bus] Command FocusWorkspaceCommand invoked.
08/11/2023 19:38:35[Bus] Command SetNativeFocusCommand invoked.
08/11/2023 19:38:35[Bus] Command ManageWindowCommand invoked.
08/11/2023 19:38:35[ManageWindowHandler] New window managed: PD-NetmanageServer WindowsForms10.Window.8.app.0.265601d_r7_ad1
08/11/2023 19:38:35[Bus] Command AttachContainerCommand invoked.
08/11/2023 19:38:35[Bus] Command SetFocusedDescendantCommand invoked.
08/11/2023 19:38:37[Bus] Command RunWindowRulesCommand invoked.
08/11/2023 19:38:37[Bus] Command SetMinimizedCommand invoked.


```

**Comment by Dimfred** [comment]
As discussed in the discord. wrapping: `GetCpuUsage()` in a try catch block:

```c#
public double GetCpuUsage()
{
  try
  {
    return _cpuCounter.Observe();
  }
  catch
  {
    return 0;
  }
}
```

helped and the issue has probably disappeared.

**Comment by lazarus2019** [comment]
> As discussed in the discord. wrapping: `GetCpuUsage()` in a try catch block helped and the issue has probably disappeared. IIRC I had similar issues with `Memory` and `GPU`, so I guess it won't hurt to do the same there.
> 
> ```cs
> public double GetCpuUsage()
> {
>   try
>   {
>     return _cpuCounter.Observe();
>   }
>   catch
>   {
>     return 0;
>   }
> }
> ```

Hi @Dimfred, how can you create custom Function and using it  for Glaze WM. Cause I using window and only have a config.yaml file for customize. 

P/s: I download GlazeWM by exe file and open that file when using it.

**Comment by Dimfred** [comment]
Hi,
I cloned to and build glaze myself. I think you can get something like Visual Studio and load / build it there.
Not sure how to do that, since I cross-compiled from linux everything was quite a little more tricky, and too hard to explain.
Obviously for "normal" supported customization, I also only have the `config.yaml` for customization.
