### ISSUE TITLE
bug: glaze crashes due to ipc

### ISSUE THREAD

**Issue by Dimfred** [lars-berger/GlazeWM#354]
Glaze crashes when I am subscribed to `focus_changed`.

Replicated:

`subscribe -e focus_changed`

Tab a little bit from left to right => see crash after a ~15seconds.

```
08/12/2023 14:06:46[WindowFocusedHandler] Window focused: WindowsTerminal CASCADIA_HOSTING_WINDOW_CLASS
08/12/2023 14:06:46[Bus] Command SetFocusedDescendantCommand invoked.
08/12/2023 14:06:46[Bus] Command SetActiveWindowBorderCommand invoked.
08/12/2023 14:06:46[Bus] Command FocusInDirectionCommand invoked.
08/12/2023 14:06:46[Bus] Command SetNativeFocusCommand invoked.
08/12/2023 14:06:46[Bus] Command CenterCursorOnContainerCommand invoked.
08/12/2023 14:06:46[WindowFocusedHandler] Window focused: WindowsTerminal CASCADIA_HOSTING_WINDOW_CLASS
08/12/2023 14:06:46[Bus] Command SetFocusedDescendantCommand invoked.
08/12/2023 14:06:46[Bus] Command SetActiveWindowBorderCommand invoked.
08/12/2023 14:06:46[Bus] Command FocusInDirectionCommand invoked.
08/12/2023 14:06:46[Bus] Command FocusInDirectionCommand invoked.
08/12/2023 14:06:46[Bus] Command SetNativeFocusCommand invoked.
08/12/2023 14:06:46[Bus] Command CenterCursorOnContainerCommand invoked.
08/12/2023 14:06:46[WindowFocusedHandler] Window focused: WindowsTerminal CASCADIA_HOSTING_WINDOW_CLASS
08/12/2023 14:06:46[Bus] Command SetFocusedDescendantCommand invoked.
08/12/2023 14:06:46[Bus] Command SetActiveWindowBorderCommand invoked.
08/12/2023 14:06:47[Bus] Command FocusInDirectionCommand invoked.
08/12/2023 14:06:47[Bus] Command SetNativeFocusCommand invoked.
08/12/2023 14:06:47[Bus] Command CenterCursorOnContainerCommand invoked.
08/12/2023 14:06:47[WindowFocusedHandler] Window focused: powershell ConsoleWindowClass
08/12/2023 14:06:47[Bus] Command SetFocusedDescendantCommand invoked.
08/12/2023 14:06:47[Bus] Command SetActiveWindowBorderCommand invoked.
Unhandled exception. System.IndexOutOfRangeException: Index was outside the bounds of the array.
at NetCoreServer.WebSocket.PrepareSendFrame(Byte opcode, Boolean mask, ReadOnlySpan`1 buffer, Int32 status)
at NetCoreServer.WsSession.SendPongAsync(ReadOnlySpan`1 buffer)
at NetCoreServer.WsSession.SendPongAsync(Byte[] buffer, Int64 offset, Int64 size)
at NetCoreServer.WsSession.OnWsPing(Byte[] buffer, Int64 offset, Int64 size)
at NetCoreServer.WebSocket.PrepareReceiveFrame(Byte[] buffer, Int64 offset, Int64 size)
at NetCoreServer.WsSession.OnReceived(Byte[] buffer, Int64 offset, Int64 size)
at NetCoreServer.TcpSession.ProcessReceive(SocketAsyncEventArgs e)
at NetCoreServer.TcpSession.OnAsyncCompleted(Object sender, SocketAsyncEventArgs e)
at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
at System.Net.Sockets.SocketAsyncEventArgs.<>c.<.cctor>b__176_0(UInt32 errorCode, UInt32 numBytes, NativeOverlapped* nativeOverlapped)
at System.Threading.ThreadPoolTypedWorkItemQueue`2.System.Threading.IThreadPoolWorkItem.Execute()
at System.Threading.ThreadPoolWorkQueue.Dispatch()
at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart()
08/12/2023 14:06:47[Bus] Command FocusInDirectionCommand invoked.
08/12/2023 14:06:47[Bus] Command SetNativeFocusCommand invoked.
08/12/2023 14:06:47[Bus] Command CenterCursorOnContainerCommand invoked.
08/12/2023 14:06:47[WindowFocusedHandler] Window focused: WindowsTerminal CASCADIA_HOSTING_WINDOW_CLASS
08/12/2023 14:06:47[Bus] Command SetFocusedDescendantCommand invoked.
08/12/2023 14:06:47[Bus] Command SetActiveWindowBorderCommand invoked.
08/12/2023 14:06:47[Bus] Command FocusInDirectionCommand invoked.
08/12/2023 14:06:47[Bus] Command SetNativeFocusCommand invoked.
08/12/2023 14:06:47[Bus] Command CenterCursorOnContainerCommand invoked.
08/12/2023 14:06:47[WindowFocusedHandler] Window focused: WindowsTerminal CASCADIA_HOSTING_WINDOW_CLASS
08/12/2023 14:06:47[Bus] Command SetFocusedDescendantCommand invoked.
08/12/2023 14:06:47[Bus] Command SetActiveWindowBorderCommand invoked.

```

**Comment by theSoberSobber** [comment]
how are you subscribing to the event? where do you run commands with the glazeWM executable? like the `subscribe -e focus_changed` command?

**Comment by Dimfred** [comment]
No I was running them in a python server. The server was running inside wsl.

The code was simple, basically send the subscribe message `subscribe -e focus_changed`, the `while True: await ws.recv()`.

Used more or less this as an example:
https://websockets.readthedocs.io/en/stable/howto/quickstart.html
